# -*- coding: utf-8 -*-
"""Quiz1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fi5-5RmNxBkYjfGU9HLP6-Orb8ACCfKV
"""

import streamlit as st

# Page configuration
st.set_page_config(page_title="Interactive Quiz", page_icon="💡", layout="centered")

st.title("💡 Quick Interactive Knowledge Check")
st.write("Answer the questions below to test your knowledge! Case-insensitive.")

# Initialize score counter
score = 0

st.write("---")

# ==================== QUESTION 1 ====================
st.subheader("Question 1")
q1_input = st.text_input(
    "What Python framework allows you to build web applications without needing HTML or CSS?",
    key="q1"
)

# Process Question 1
if q1_input:
    # .strip().lower() ignores accidental spaces and capital letters
    if q1_input.strip().lower() == "streamlit":
        st.success("✅ Correct! Excellent job.")
        score += 1
    else:
        st.error("❌ Not quite. Try again!")

st.write("---")

# ==================== QUESTION 2 ====================
st.subheader("Question 2")
q2_input = st.text_input(
    "Which platform hosts git repositories and lets you launch cloud-based Codespaces?",
    key="q2"
)

# Process Question 2
if q2_input:
    if q2_input.strip().lower() == "github":
        st.success("✅ Correct! Spot on.")
        score += 1
    else:
        st.error("❌ Keep trying!")

st.write("---")

# ==================== SCORE BOARD ====================
if q1_input or q2_input:
    st.markdown(f"### 📊 Your Current Score: **{score} / 2**")

    # Trigger celebration if all answers are correct
    if score == 2:
        st.balloons()
        st.info("🎉 Perfect Score! You've mastered this topic.")