# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZBkpYT3wf_OZ6Xx7dTZuI-dtc0EUslW
"""

!pip install streamlit --ignore-installed

# Commented out IPython magic to ensure Python compatibility.
# %%writefile HiStudent.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# 
# st.title("🚀 My First Streamlit App")
# st.write("Welcome! Modify the widgets below to see how interactive web apps work.")
# 
# user_name = st.text_input("What is your name?", "Student")
# st.subheader(f"Hello, {user_name}! 👋")
# 
# number = st.slider("Select a number of data points", 10, 100, 50)
# 
# data = pd.DataFrame(
#     np.random.randn(number, 2),
#     columns=['X Factor', 'Y Factor']
# )
# 
# st.line_chart(data)

# 1. Download Cloudflare Tunnel binary
!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared

# 2. Run Streamlit in the background
!streamlit run app.py &>/dev/null &

# 3. Expose Streamlit port 8501 via Cloudflare
!./cloudflared tunnel --url http://localhost:8501